
  You can now view your Streamlit app in your browser.

  Network URL: http://192.168.100.214:8502
  External URL: http://18.162.207.247:8502


  You can now view your Streamlit app in your browser.

  Network URL: http://192.168.100.214:8502
  External URL: http://18.162.207.247:8502


  You can now view your Streamlit app in your browser.

  Network URL: http://192.168.100.214:8504
  External URL: http://18.162.207.247:8504


  You can now view your Streamlit app in your browser.

  Network URL: http://192.168.100.214:8000
  External URL: http://18.162.207.247:8000


  You can now view your Streamlit app in your browser.

  Network URL: http://192.168.100.214:8001
  External URL: http://18.162.207.247:8001

2022-05-23 03:16:11.861 Port 8001 is already in use
  Stopping...

  You can now view your Streamlit app in your browser.

  Network URL: http://192.168.100.214:8001
  External URL: http://18.162.207.247:8001

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/ubuntu/.local/lib/python3.8/site-packages/markupsafe/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 70, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/delta_generator.py", line 72, in <module>
    from streamlit.elements.arrow import ArrowMixin
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/elements/arrow.py", line 20, in <module>
    from pandas.io.formats.style import Styler
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/io/formats/style.py", line 52, in <module>
    jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/ubuntu/.local/lib/python3.8/site-packages/markupsafe/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 70, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/delta_generator.py", line 72, in <module>
    from streamlit.elements.arrow import ArrowMixin
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/elements/arrow.py", line 20, in <module>
    from pandas.io.formats.style import Styler
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/io/formats/style.py", line 52, in <module>
    jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.
2022-05-25 01:54:41.240 INFO    matplotlib.font_manager: generated new fontManager

  You can now view your Streamlit app in your browser.

  Network URL: http://172.31.7.174:8001
  External URL: http://18.163.30.4:8001


  You can now view your Streamlit app in your browser.

  Network URL: http://172.31.7.174:8000
  External URL: http://18.163.30.4:8000


  You can now view your Streamlit app in your browser.

  Network URL: http://172.31.7.174:8001
  External URL: http://18.163.30.4:8001


  You can now view your Streamlit app in your browser.

  Network URL: http://172.31.7.174:8001
  External URL: http://18.163.30.4:8001

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 138, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/ubuntu/.local/lib/python3.8/site-packages/markupsafe/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 70, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/delta_generator.py", line 72, in <module>
    from streamlit.elements.arrow import ArrowMixin
  File "/home/ubuntu/.local/lib/python3.8/site-packages/streamlit/elements/arrow.py", line 20, in <module>
    from pandas.io.formats.style import Styler
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/io/formats/style.py", line 52, in <module>
    jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

  You can now view your Streamlit app in your browser.

  Network URL: http://172.31.7.174:8001
  External URL: http://18.163.30.4:8001

  Stopping...

  You can now view your Streamlit app in your browser.

  Network URL: http://172.31.7.174:8001
  External URL: http://18.163.30.4:8001

2022-05-26 06:19:14.574 Traceback (most recent call last):
  File "/home/ubuntu/streamlitch/streamlit/lib/python3.8/site-packages/streamlit/scriptrunner/script_runner.py", line 475, in _run_script
    exec(code, module.__dict__)
  File "/home/ubuntu/streamlitch/heatmap.py", line 12, in <module>
    import py2neo
ModuleNotFoundError: No module named 'py2neo'

2022-05-26 06:19:49.067 NumExpr defaulting to 2 threads.
  Stopping...
Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: heatmapNew.py
